board/urls.py
from django.urls import path

from .views import *

app_name = 'board'

urlpatterns = [
     # posts
     path('', PostList.as_view(), name='post_list'),
     path('<int:pk>', PostDetail.as_view(), name='post_detail'),
     path('create/', PostCreate.as_view(), name='post_create'),
     path('update/<int:post_pk>', PostUpdate.as_view(), name='post_update'),
     path('<int:post_pk>/delete/', PostDelete.as_view(), name='post_delete'),
     # comments
     path('<int:post_pk>/comments', CommentsList.as_view(), name='comments_list'),
     path('<int:post_pk>/create_comment', CommentCreate.as_view(), name='comment_create'),
     path('<int:post_pk>/comments/<int:comment_pk>/accept', CommentAccept.as_view(), name='comment_accept'),
     path('<int:post_pk>/comments/<int:comment_pk>/reject', CommentReject.as_view(), name='comment_reject'),
     path('comments/<int:comment_pk>/delete', CommentDelete.as_view(), name='comment_delete'),
     path('dashboard/', DashboardView.as_view(), name='dashboard'),
     # views
     path('category/<slug:name>', CategoryView.as_view(), name='category'),
     path('by_author/<slug:name>', ByAuthorView.as_view(), name='by_author'),
]

set/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from board.views import IndexView

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('auth/', include('authentication.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
#from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField('Title', max_length=100)
    #text = RichTextUploadingField('Text')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Category')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.category} :: {self.title}'


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1600)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    approved = models.BooleanField('Approved', null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author} - {self.datetime}'

board/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
# from ckeditor_uploader.fields import RichTextUploadingField
from django import forms

from .models import *


class PostCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        label='Category',
        widget=forms.Select(attrs={'class': 'form-select'}),
        queryset=Category.objects.all()
    )
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control'}))
    text = forms.CharField(label='Text', widget=CKEditorUploadingWidget(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        exclude = ('author',)


class CommentCreateForm(forms.ModelForm):
    text = forms.CharField(label='Text', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('text',)

board/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView

from .forms import PostCreateForm, CommentCreateForm
from .models import *
from .utils.permissions import IsAuthorMixin, NotIsAuthorMixin


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'board/front.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['is_not_authors'] = not self.request.user.groups.filter(name = 'authors').exists()

        return context


class PostList(ListView):
    model = Post
    context_object_name = 'post_list'
    queryset = Post.objects.order_by('-datetime')


class PostDetail(DetailView):
    model = Post
    context_object_name = 'post'


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'board/crid/post_create.html'

    def get_success_url(self):
        return reverse('board:post_list')

    def form_valid(self, form):
        post = form.save(commit=False)
        user = self.request.user
        post.author = user
        return super().form_valid(form)


class PostUpdate(IsAuthorMixin, UpdateView):
    model = Post
    pk_url_kwarg = 'post_pk'
    form_class = PostCreateForm
    template_name = 'board/crid/post_create.html'

    def get_success_url(self):
        return reverse('board:post_list')

    def form_valid(self, form):
        messages.success(self.request, 'Success!')
        return super().form_valid(form)


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'board/crid/post_delete.html'
    success_url = '/board/'
    permission_required = ('board.post_delete')
    context_object_name = 'post'

    def get_object(self, **kwargs ):
        post_id = self.kwargs.get('post_pk')
        post = Post.objects.get(pk=post_id)
        return post

class CommentsList(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        post_pk = kwargs['post_pk']
        post = Post.objects.get(pk=post_pk)
        qs = Comment.objects.order_by('datetime').filter(post=post)

        context = {
            'comments': qs,
            'post': post
        }

        return render(request, 'board/comments_list.html', context)


class CommentCreate(NotIsAuthorMixin, View):
    def get(self, request, **kwargs):
        form = CommentCreateForm(request.POST or None)
        post = Post.objects.get(pk=kwargs['post_pk'])

        context = {
            'form': form,
            'post': post
        }

        return render(request, 'board/crid/comment_create.html', context)

    def post(self, request, *args, **kwargs):
        form = CommentCreateForm(request.POST)
        user = request.user
        post_pk = kwargs['post_pk']

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = user
            comment.post = Post.objects.get(pk=post_pk)
            comment.save()

        return redirect('board:post_list')


class CommentAccept(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        comment_pk = kwargs['comment_pk']

        comment = Comment.objects.get(pk=comment_pk)
        comment.approved = True
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentReject(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        comment_pk = kwargs['comment_pk']

        comment = Comment.objects.get(pk=comment_pk)
        comment.approved = False
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'board/crid/comment_delete.html'
    success_url = '/board/'
    permission_required = ('board.comment_delete')
    context_object_name = 'comment'

    def get_object(self, **kwargs ):
        comment_id = self.kwargs.get('comment_pk')
        comment = Comment.objects.get(pk=comment_id)
        return comment


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'posts': request.user.post_set.all(),
        }
        return render(request, 'board/dashboard.html', context)


class CategoryView(ListView):
    def get(self, request, *args, **kwargs):
      category = Category.objects.get(name=kwargs['name'])
      qs = Post.objects.order_by('datetime').filter(category=category)

      context = {
          'category': category,
          'posts': qs,

      }
      return render(request, 'board/category_list.html', context)


class ByAuthorView(ListView):
    def get(self, request, *args, **kwargs):
      author = User.objects.get(username=kwargs['name'])
      qs = Post.objects.order_by('datetime').filter(author = author)

      context = {
          'author': author,
          'posts': qs,
      }
      return render(request, 'board/by_author.html', context)

board/templates/board/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Favicons -->
  <link rel="apple-touch-icon" href="{% static 'img/favicons/favicon-96x96.png' %}" sizes="96x96">
  <link rel="icon" href="{% static 'img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
  <link rel="icon" href="{% static 'img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">

  <link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
  <meta name="theme-color" content="#7952b3">

  <link href="{% static 'css/style.css' %}" rel="stylesheet" />


  <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>

  <!-- <script defer src="offcanvas.js"></script> -->
  <script defer src="{% static 'js/script.js' %}"></script>
  <title>
    {% block title %}
    {% endblock title %}

  </title>

</head>

<body>
  <header class="site-header sticky-top py-1">


    {%if user.is_authenticated %}

    {% include 'includes/dashboard.html' %}
    {% else%}
    {% include 'includes/navbar.html' %}

    {%endif%}

  </header>

  <main>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}
  </main>
  {% include 'includes/footer.html' %}
</body>

</html>

board/templates/board/by_author.html
{% extends 'board/base.html' %}
{% block title %}
{{author}}
{% endblock title %}

{% block content %}

{% for post in posts %}
<div class="container">
  {%include "includes/post_layout.html"%}
</div>
{%endfor%}
{% endblock content %}

board/templates/board/category_list.html
{% extends 'board/base.html' %}
{% block title %}
{{category}}
{% endblock title %}

{% block content %}

{% for post in posts %}
<div class="container">
  {%include "includes/post_layout.html"%}
</div>
{%endfor%}
{% endblock content %}

board/templates/board/comments_list.html
{% extends 'board/base.html' %}
{% block title %}
{{ post.title }} | {{post.category}}
{% endblock title %}

{% block content %}
<div class="container">
  <div class="card p-2">
    <div class="card-header">
      <h3 class="card-title">
        <a class="navbar-brand" href="{% url 'board:post_detail' post.pk %}">
          {{ post.title }}
        </a>
      </h3>
      <a class="navbar-brand" href="{% url 'board:post_detail' post.pk %}">
        <span class="badge bg-secondary float-end">{{ post.category }}</span>
      </a>
      <small class="text-muted ms-1">
        <b>
          published by:
        </b>
        <span class="fst-italic">
        </span>
        <a href="{% url 'board:by_author' post.author %}">
          <span class="fst-italic">{{ post.author }}</span>
        </a>
        <b>
          on:
        </b>
        <span class="fst-italic">
          {{ post.datetime}}
        </span>
        </p>
      </small>
    </div>

    <div class="card-body">
      <p class="card-text ">{{ post.text|safe|truncatewords:50}}</p>
    </div>
  </div>

  {% for comment in comments %}
  <div class="shadow-sm p-3 my-2 bg-body rounded">
    <div class="d-flex justify-content-between p-1">
      <a href="{% url 'board:by_author' comment.author %}">

        <h5 class="mb-1">{{ comment.author }}</h5>

      </a>
      <small class="text-muted">Submitted on: {{ comment.datetime }}</small>
    </div>
    <div class="row">
      <div class="col-lg-10 col-sm-12">
        <p class="ms-3">{{ comment.text }}</p>
      </div>

      <div class="col-lg-2 col-sm-12">
        <div class="d-flex flex-md-row flex-lg-column align-items-lg-end  justify-content-end gap-1">
          {% if comment.approved %}

          <button class="btn btn-outline-success">
            Accepted
          </button>
          {%else %}
          <a href="{% url 'board:comment_accept' post.pk comment.pk %}">
            <button class="btn btn-success">
              Accept
            </button>
          </a>
          {% endif %}

          {% if not comment.approved and not comment.approved is None %}

          <button class="btn btn-outline-warning text-dark">
            Rejected
          </button>
          {%else%}
          <a href="{% url 'board:comment_reject' post.pk comment.pk %}">
            <button class="btn btn-warning">
              Reject
            </button>
          </a>
          {% endif %}
          <a href="{% url 'board:comment_delete' comment.pk %}">
            <button class="btn btn-danger">
              Delete
            </button>
          </a>

        </div>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="text-center">
    <h3 class="fw-bold">No comments yet</h3>
    <p class="lead ">Check later and keep posting!</p>
    <a href="{% url 'board:post_list' %}">
      <button type="button" class="btn btn-primary btn-lg">
        To Game Stock
      </button>
    </a>
  </div>
</div>



{% endfor %}


{% endblock content %}

board/templates/board/dashboard.html
{% extends 'board/base.html' %}

{% block title %}
Dashboard
{% endblock title %}

{% block content %}
<div class="container">

  {% for post in posts %}
  <div class="row">
    {%include "includes/post_layout.html" %}
  </div>
  {% endfor %}

</div>
{% endblock content %}

board/templates/board/front.html
{% extends 'board/base.html' %}
{% block title %}
Доска объявлений
{% endblock title %}

{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 fw-normal">Так себе</h1>
    <p class="lead fw-normal">
      You can exchange your game assets here
    </p>
    <a class="btn btn-outline-secondary" href="{% url 'board:post_list' %}">погнали</a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>

<!-- <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>
<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-primary me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>
<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>
<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div> -->
{% endblock content %}

board/templates/board/post_detail.html
{% extends 'board/base.html' %}

{% block title %}
{{ post.title }} | {{post.category}}
{% endblock title %}

{% block content %}
<div class="container">
  {% include 'includes/post_layout.html'%}
</div>
{% endblock content %}

board/templates/board/post_list.html
{% extends 'board/base.html' %}

{% block title %}Доска постов | All Posts{% endblock title %}

{% block content %}

<div class="container">
<!--  {% for post in post_list %}-->
<!--  {% include 'includes/post_layout.html'%}-->

<!--  {% empty %}-->
  <div class="text-center">
    <h3 class="fw-bold">No posts yet</h3>
    <p class="lead ">Start posting!</p>
    <a href="{% url 'board:post_create' %}">
      <button type="button" class="btn btn-primary btn-lg px-4 gap-3">
        Add New Post
      </button>
    </a>
  </div>
  {% endfor %}
</div>

{% endblock content %}