board/urls.py
from django.urls import path

from .views import *

app_name = 'board'

urlpatterns = [
     # posts
     path('', PostList.as_view(), name='post_list'),
     path('<int:pk>', PostDetail.as_view(), name='post_detail'),
     path('create/', PostCreate.as_view(), name='post_create'),
     path('update/<int:post_pk>', PostUpdate.as_view(), name='post_update'),
     path('<int:post_pk>/delete/', PostDelete.as_view(), name='post_delete'),
     # comments
     path('<int:post_pk>/comments', CommentsList.as_view(), name='comments_list'),
     path('<int:post_pk>/create_comment', CommentCreate.as_view(), name='comment_create'),
     path('<int:post_pk>/comments/<int:comment_pk>/accept', CommentAccept.as_view(), name='comment_accept'),
     path('<int:post_pk>/comments/<int:comment_pk>/reject', CommentReject.as_view(), name='comment_reject'),
     path('comments/<int:comment_pk>/delete', CommentDelete.as_view(), name='comment_delete'),
     path('dashboard/', DashboardView.as_view(), name='dashboard'),
     # views
     path('category/<slug:name>', CategoryView.as_view(), name='category'),
     path('by_author/<slug:name>', ByAuthorView.as_view(), name='by_author'),
]

set/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from board.views import IndexView

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('auth/', include('authentication.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
#from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField('Title', max_length=100)
    #text = RichTextUploadingField('Text')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Category')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.category} :: {self.title}'


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1600)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    approved = models.BooleanField('Approved', null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author} - {self.datetime}'

board/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
# from ckeditor_uploader.fields import RichTextUploadingField
from django import forms

from .models import *


class PostCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        label='Category',
        widget=forms.Select(attrs={'class': 'form-select'}),
        queryset=Category.objects.all()
    )
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control'}))
    text = forms.CharField(label='Text', widget=CKEditorUploadingWidget(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        exclude = ('author',)


class CommentCreateForm(forms.ModelForm):
    text = forms.CharField(label='Text', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('text',)

board/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView

from .forms import PostCreateForm, CommentCreateForm
from .models import *
from .utils.permissions import IsAuthorMixin, NotIsAuthorMixin


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'board/front.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['is_not_authors'] = not self.request.user.groups.filter(name = 'authors').exists()

        return context


class PostList(ListView):
    model = Post
    context_object_name = 'post_list'
    queryset = Post.objects.order_by('-datetime')


class PostDetail(DetailView):
    model = Post
    context_object_name = 'post'


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'board/crid/post_create.html'

    def get_success_url(self):
        return reverse('board:post_list')

    def form_valid(self, form):
        post = form.save(commit=False)
        user = self.request.user
        post.author = user
        return super().form_valid(form)


class PostUpdate(IsAuthorMixin, UpdateView):
    model = Post
    pk_url_kwarg = 'post_pk'
    form_class = PostCreateForm
    template_name = 'board/crid/post_create.html'

    def get_success_url(self):
        return reverse('board:post_list')

    def form_valid(self, form):
        messages.success(self.request, 'Success!')
        return super().form_valid(form)


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'board/crid/post_delete.html'
    success_url = '/board/'
    permission_required = ('board.post_delete')
    context_object_name = 'post'

    def get_object(self, **kwargs ):
        post_id = self.kwargs.get('post_pk')
        post = Post.objects.get(pk=post_id)
        return post

class CommentsList(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        post_pk = kwargs['post_pk']
        post = Post.objects.get(pk=post_pk)
        qs = Comment.objects.order_by('datetime').filter(post=post)

        context = {
            'comments': qs,
            'post': post
        }

        return render(request, 'board/comments_list.html', context)


class CommentCreate(NotIsAuthorMixin, View):
    def get(self, request, **kwargs):
        form = CommentCreateForm(request.POST or None)
        post = Post.objects.get(pk=kwargs['post_pk'])

        context = {
            'form': form,
            'post': post
        }

        return render(request, 'board/crid/comment_create.html', context)

    def post(self, request, *args, **kwargs):
        form = CommentCreateForm(request.POST)
        user = request.user
        post_pk = kwargs['post_pk']

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = user
            comment.post = Post.objects.get(pk=post_pk)
            comment.save()

        return redirect('board:post_list')


class CommentAccept(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        comment_pk = kwargs['comment_pk']

        comment = Comment.objects.get(pk=comment_pk)
        comment.approved = True
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentReject(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        comment_pk = kwargs['comment_pk']

        comment = Comment.objects.get(pk=comment_pk)
        comment.approved = False
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'board/crid/comment_delete.html'
    success_url = '/board/'
    permission_required = ('board.comment_delete')
    context_object_name = 'comment'

    def get_object(self, **kwargs ):
        comment_id = self.kwargs.get('comment_pk')
        comment = Comment.objects.get(pk=comment_id)
        return comment


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'posts': request.user.post_set.all(),
        }
        return render(request, 'board/dashboard.html', context)


class CategoryView(ListView):
    def get(self, request, *args, **kwargs):
      category = Category.objects.get(name=kwargs['name'])
      qs = Post.objects.order_by('datetime').filter(category=category)

      context = {
          'category': category,
          'posts': qs,

      }
      return render(request, 'board/category_list.html', context)


class ByAuthorView(ListView):
    def get(self, request, *args, **kwargs):
      author = User.objects.get(username=kwargs['name'])
      qs = Post.objects.order_by('datetime').filter(author = author)

      context = {
          'author': author,
          'posts': qs,
      }
      return render(request, 'board/by_author.html', context)

board/templates/includes/comment.html
<form method="post" class="row g-3">
  {% csrf_token %}

  <div class="col-12">
    <h4 class="mb-4 mt-5">Your response:</h4>
    {{ form.text }}
  </div>

  <div class="col-12">
    <button type="submit" class="btn btn-primary">Send</button>
  </div>
</form>

board/templates/includes/dashboard.html
{%include 'includes/svg_icons.html'%}
<div class="px-3 py-2 text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <!-- <use xlink:href="#bootstrap" /> -->
          <use xlink:href="#home" />
        </svg>
        Home
      </a>


      <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">

        <li>
          <a href="{% url 'board:post_list' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#table" />
            </svg>
            Game Stock
          </a>
        </li>
        <li>
          <a href="{% url 'board:post_create' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#grid" />
            </svg>
            New Post
          </a>
        </li>
        <li>
          <a href="{% url 'board:dashboard' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#speedometer2" />
            </svg>
            Dashboard
          </a>
        </li>
        {% if user.is_superuser %}
        <li>
          <a href="/admin/" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#grid" />
            </svg>
            Admin Panel
          </a>
        </li>

        {% endif %}

        <li>

          <a href="/auth/logout/" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#people-circle" />
            </svg>
            Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

board/templates/includes/footer.html
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor"
        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img"
        viewBox="0 0 24 24">
        <title>Product</title>
        <circle cx="12" cy="12" r="10" />
        <path
          d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
      </svg>
      <small class="d-block mb-3 text-muted">&copy; 2017–{% now 'Y'%}</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
        <li><a class="link-secondary" href="#">Another one</a></li>
        <li><a class="link-secondary" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Resource name</a></li>
        <li><a class="link-secondary" href="#">Resource</a></li>
        <li><a class="link-secondary" href="#">Another resource</a></li>
        <li><a class="link-secondary" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Business</a></li>
        <li><a class="link-secondary" href="#">Education</a></li>
        <li><a class="link-secondary" href="#">Government</a></li>
        <li><a class="link-secondary" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

board/templates/includes/navbar.html
{%include 'includes/svg_icons.html'%}

{% block nav %}

<nav class="container d-flex flex-column align-self-center  list-unstyled flex-md-row justify-content-between">
  <a href="/" class="align-self-center bi my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
    <svg class=" me-2" width="40" height="32" role="img" aria-label="Bootstrap">
      <!-- <use xlink:href="#bootstrap" /> -->
      <use xlink:href="#home" />
    </svg>
    Home
  </a>


  <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">

    <li>
      <a href="{% url 'board:post_list' %}" class="nav-link text-white">
        <svg class="bi d-block mx-auto mb-1" width="24" height="24">
          <use xlink:href="#table" />
        </svg>
        Game Stock
      </a>
    </li>
  </ul>
  <ul class="d-flex list-unstyled">
    <li>
      <a href="{% url 'account_login' %}">
        <button type="button" class="btn btn-outline-info me-2 text-white">
          Login
        </button>
      </a>
    </li>
    <li>

      <a href="{% url 'account_signup' %}">
        <button type="button" class="btn btn-primary">
          Signup
        </button>
      </a>
    </li>
  </ul>

</nav>

{% endblock nav %}

board/templates/includes/post_layout.html
<div class="row p-2 my-2 shadow bg-body rounded">
  <div class="card p-2">
    <div class="card-header">
      <h3 class="card-title">
        <a class="navbar-brand" href="{% url 'board:post_detail' post.pk %}">
          {{ post.title }}
        </a>
      </h3>
      <a class="navbar-brand" href="{% url 'board:category' post.category.name %}">
        <span class="badge bg-secondary float-end">{{ post.category }}</span>
      </a>
      <small class="text-muted ms-1">
        <b>
          published by:
        </b>
        <span class="fst-italic">
        </span>
        <a href="{% url 'board:by_author' post.author %}">
          <span class="fst-italic">{{ post.author }}</span>
        </a>
        <b>
          on:
        </b>
        <span class="fst-italic">
          {{ post.datetime}}
        </span>
        </p>

      </small>
    </div>

    <div class="card-body">
      {% if post_list or posts %}
      <p class="card-text ">{{ post.text|safe|truncatewords:25}}</p>
      {% else %}
      <p class="card-text ">{{ post.text|safe}}</p>
      {%endif%}

    </div>

    <div class="card-footer">

      {% if user.is_authenticated and post in user.post_set.all %}
      <a class="text-decoration-none" href="{% url 'board:comments_list' post.pk %}">
        <button type="button" class="btn btn-outline-primary position-relative ">
          Responses
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            {{ post.comment_set.all|length }}
          </span>
        </button>
      </a>
      <a class="text-decoration-none" href="{% url 'board:post_update' post.pk %}">
        <button class="btn btn-outline-warning text-dark">
          Edit
        </button>
      </a>
      <a href="{% url 'board:post_delete' post.pk %}">
        <button class="btn btn-outline-danger">
          Delete
        </button>
      </a>
      {% else %}
      <a class="text-decoration-none" href="{% url 'board:comment_create' post.pk %}">
        <button class="btn btn-outline-info">
          Respond
        </button>
      </a>
      {% endif %}
    </div>
  </div>
</div>

board/templates/includes/svg_icons.html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd"
      d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z">
    </path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path
      d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z" />
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path
      d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z" />
    <path fill-rule="evenodd"
      d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z" />
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path
      d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z" />
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
    <path fill-rule="evenodd"
      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path
      d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z" />
  </symbol>
</svg>